---
format: 
  gfm:
    embed-resources: false
editor:
    render-on-save: true
execute: 
  echo: false
  warning: false
  fig-width: 10
  fig-height: 5
---


```{r}
library(tidyverse)
library(glue)
library(ggthemes)
library(scales)
```


# Comparison Risky and Secure Investment Strategy

```{r}
num <- 125000
num_years <- 25
set.seed(44)

data <- read_csv("data/simulations.csv")


final_capital <- data |>
    group_by(name, simulation) |>
    summarise(total_growth = prod(growth)) |>
    ungroup()
```

```{r parameters}

# data |>
#     group_by(name) |>
#     summarise(mean = mean(growth), sd = sd(growth))
```

```{r wealth_distribution}
final_capital |>
    ggplot(aes(total_growth, fill = name)) +
    geom_histogram(bins = 100) +
    geom_vline(xintercept = 1, linetype = "dotted") +
    scale_x_continuous(trans = "log10", labels = percent) +
    scale_y_continuous(trans = "log10") +
    scale_fill_tableau() +
    facet_wrap(~name) +
    theme_minimal() +
    labs(title = "Alice vs Bob", subtitle = "Wealth Distribution", x = "Total Growth after {num_years} years" |> glue(), y = "Number")
```


```{r ruin_ratio}
final_capital |>
    mutate(ruined = ifelse(total_growth < 1, T, F)) |>
    group_by(name, ruined) |>
    summarise(n = n()) |>
    mutate(ratio = n / sum(n)) |>
    ggplot(aes(x = name, y = ratio, fill = ruined)) +
    geom_bar(stat = "identity") +
    geom_text(
        aes(label = scales::percent(ratio, accuracy = 0.1), group = ruined),
        position = position_stack(vjust = 0.5),
        color = "white",
        size = 4
    ) +
    scale_fill_manual(
        labels = c("FALSE" = "Safe", "TRUE" = "Ruined"),
        values = c("FALSE" = "#2ca02c", "TRUE" = "#d62728")
    ) +
    coord_flip() +
    theme_minimal() +
    theme(
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid = element_blank(),
    ) +
    labs(title = "Alice vs Bob", subtitle = "Ruin Percentage", x = "", y = "", fill = "")
```